#!/data/data/com.termux/files/usr/bin/bash

# Get the top 10 tasks based on urgency, showing only IDs and descriptions
tasks=$(task rc:"/data/data/com.termux/files/home/.config/taskwarrior/taskrc" rc.verbose=nothing limit:10 sort:urgency- rc.defaultwidth=0 rc.report.next.columns=id,description rc.report.next.labels=1,2 next | awk 'NR>1 {print $1 ". " substr($0, index($0, $2))}')

termux-notification --title "Top 10 Tasks" --content "$tasks"
