#!/data/data/com.termux/files/usr/bin/bash

input=$1
XDG_CONFIG_HOME=/data/data/com.termux/files/home/.config

# Internal Field Separator
IFS="," read -ra params <<< "$input"

# Check if each parameter exists
if [[ "${#params[@]}" -lt 5 ]]; then
    /data/data/com.termux/files/home/.config/taskwarrior/start_daemon "ERROR: Missing fields in input."
    exit 1
fi

desc=${params[0]}
due=${params[1]}
ntf1=${params[2]}
pri=${params[3]}
tags=${params[4]}
tags="${tags// /,}"
etc="${params[@]:5}"

output=$(task add rc:"$XDG_CONFIG_HOME/taskwarrior/taskrc" "$desc" due:"$due" ntf1:"$ntf1" pri:"$pri" tag:"$tags" "$etc" 2>&1)
/data/data/com.termux/files/home/.config/taskwarrior/start_daemon "$output"

#echo "ERROR: $stderror" | termux-toast

#termux-notification --action "bash -c 'am start --user 0 -n com.termux/com.termux.app.TermuxActivity'" --button1 "New task" --button1-action "bash -lc '$XDG_CONFIG_HOME/taskwarrior/new_task \$REPLY'" --id 1 --ongoing --title Daemon --alert-once
